### ISSUE TITLE
Add macos ARM support

### ISSUE THREAD

**Issue by Jurek-Raben** [vvvar/PeakEater#63]
Please add arm support for M1++ mac machines. Thanks.

**Comment by Jurek-Raben** [comment]
Ok, a simple manual build with "CMAKE_BUILD_TYPE Release" actually generated an arm native UB2 binary.

**Comment by Jurek-Raben** [comment]
What about sine and limit modes? Did you leave those out for a specific reason?

**Comment by vvvar** [comment]
Thanks, somehow overlooked that! When compiling natively then it automatically produces UB2, but turned out on a CI you shall explicitly specify that.
Added M1+ support in 0.6.1 - https://github.com/vvvar/PeakEater/releases/tag/v0.6.1

Tbh cannot remember why i've left out sin :D Could try play with it, maybe it could be added back. Limit is basically hardclip. As far as i could remember that's leftover from old implementation.

**Comment by Jurek-Raben** [comment]
Very cool, thanks for that! But I think you actually made debug builds. I added CMAKE_BUILD_TYPE=Release somewhere, I think it was either in [CMakeLists.txt](https://github.com/vvvar/PeakEater/blob/master/CMakeLists.txt) or simply as env variable. My builds are 3.4mb of size, yours 6.9mb... :)

**Comment by vvvar** [comment]
Checked [pipeline](https://github.com/vvvar/PeakEater/blob/master/.github/workflows/publish_release_draft.yml)(this one specifically creates and publishes all releases) - passing DCMAKE_BUILD_TYPE from BUILD_TYPE which is [always RELEASE](https://github.com/vvvar/PeakEater/blob/master/.github/workflows/publish_release_draft.yml#L9). Also checked release build logs, looks legit:
<img width="968" alt="Screenshot 2023-03-26 at 13 30 54" src="https://user-images.githubusercontent.com/32337080/227772768-199ebb76-8c89-4f77-86bd-4491b67c091a.png">
So unless there's something nasty coming deep within framework - shall be fine :D
The difference in size is most likely because i'm creating Universal Binaries with:
```
-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
```
which is kinda "umbrella binary" that has both x86_64 and arm64 inside of it. macOS will [automatically pick](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary#Specify-the-Launch-Behavior-of-Your-App) correct one depending on your architecture. Intentionally doing that so that users won't be confused which version they should pick up :)

**Comment by vvvar** [comment]
Seems Arm integration is stabilised now. Closing.
