### ISSUE TITLE
Support for High Sierra

### ISSUE THREAD

**Issue by kdencebeats** [vvvar/PeakEater#65]
Would love for PeakEater to run on MAC OS High Sierra (10.13.6). Is this possible? I'm using Ableton 11.2.7 Suite.

**Comment by vvvar** [comment]
Hi!
Framework says that [10.9+](https://github.com/juce-framework/JUCE#deployment-targets) is possible. I've made an experimental build that theoretically shall support 10.9+(at least, i can see from build logs that 10.9 is set as minimum target version), but i cannot verify it since i don't have this version of macOS. Can you please try it out? If it works then i'll make a quick release with it.
[PeakEater_v0.6.2_macOS.zip](https://github.com/vvvar/PeakEater/files/11083325/PeakEater_v0.6.2_macOS.zip)

**Comment by kdencebeats** [comment]
I just wanted to let you know that I have successfully tested the experimental build of PeakEater v0.6.2 on my macOS 10.13.6 (High Sierra) system, and it works flawlessly. Thank you for fixing the compatibility issue and taking the time to create this experimental build. I appreciate your effort in ensuring that your software is accessible to a wider range of users.

**Comment by vvvar** [comment]
Awesome! Thanks for checking! You're welcome :)
Published release with this fix in https://github.com/vvvar/PeakEater/releases/tag/v0.6.2
Will mention High Sierra support then also.
