### ISSUE TITLE
[Bug] When set to Tangent Clip mode, the signal peaks above 0dB

### ISSUE THREAD

**Issue by Unerium** [vvvar/PeakEater#71]
Description of the Issue: 

When I set the clipping mode to Tangent and the oversampling is set to OFF, the signal still goes above 0dB, Is there a chance you can fix that?

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Plugin format [VST3]
 - Version [e.g. 2.2]

**DAW:**
 - Name: [Ableton Live]
 - Version [11.0]

**Comment by vvvar** [comment]
Hi. Was able to repro, indeed something is wrong with this algo on high levels of clipping. Will have a look. Thanks!

**Comment by vvvar** [comment]
The culprit was external tanh function. Have exchanged for the more stable implementation. Fix is in [v7.0.2](https://github.com/vvvar/PeakEater/releases/tag/v0.7.2).

<img width="1308" alt="before" src="https://github.com/vvvar/PeakEater/assets/32337080/7c9a26b7-7bd9-43a3-84b5-e78e72154dcd">
<img width="1207" alt="after" src="https://github.com/vvvar/PeakEater/assets/32337080/5e4b35d9-62c3-4590-a0e2-445748a1fd17">
