### ISSUE TITLE
[Bug] REAPER doesn't recognize the plugin or fails to load AU

### ISSUE THREAD

**Issue by alucast** [vvvar/PeakEater#73]
After installing, REAPER doesn't recognize either clap or vst3 but does show AU, when trying to open it, it just doesn't load. 
The plugin did work on earlier versions with the earlier GUI.

https://imgur.com/GB2Lpay

Mac Os Mojave 10.14
REAPER 6.78

**Comment by vvvar** [comment]
Hi!
Checked latest version with Reaper 6.78 on macOS 12.6.3 Monterey - works for me.

<img width="653" alt="Screenshot 2023-03-28 at 00 31 50" src="https://user-images.githubusercontent.com/32337080/228081683-8d54bbc3-e8d2-48f9-b11a-186369fc5847.png">

The only difference i can see at the moment is macOS version. Thus i suspect it has something to do with backwards compatibility. 

I'm trying to add backwards compatibility now for [this feature request](https://github.com/vvvar/PeakEater/issues/65). I suspect that it may help resolve your issue as well. Can you please try build from [this comment](https://github.com/vvvar/PeakEater/issues/65#issuecomment-1485926222)? Since i have only macOS 12.6.3 Monterey to test.

**Comment by alucast** [comment]
Hey! Thank you!! That did the job indeed o: works now. So is it beta? can I start using it or should I wait for an "official" release? Thanks again! I will use this soooo much

**Comment by vvvar** [comment]
Awesome! Thanks for checking!
I will make a release with this fix and let you know. Before that for sure you can use this build.

**Comment by vvvar** [comment]
Made a release with this fix
https://github.com/vvvar/PeakEater/releases/tag/v0.6.2

**Comment by alucast** [comment]
Thanks! Awesome 😎 👍
